spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: first
          predicates:
            - Path=/first/
          uri: http://localhost:8081
        - id : auth-server
          predicates:
            - Path=/login/
          uri: http://localhost:8088
    config:
      enabled: false

  main:
    web-application-type: reactive


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
jwt:
  secret: VHKJMNnbfhbsjkdbVJHVkhbJBKJBsmfnbngygiyguFYVHJbkjnjnsjdnlkfn

server:
  port: 8090

authentication:
  enabled: true